<?php
/**
 * @see       https://github.com/phly/keep-a-changelog for the canonical source repository
 * @copyright Copyright (c) 2019 Matthew Weier O'Phinney
 * @license   https://github.com/phly/keep-a-changelog/blob/master/LICENSE.md New BSD License
 */

declare(strict_types=1);

namespace Phly\KeepAChangelog\Changelog;

use Phly\KeepAChangelog\Common\ChangelogEditor;
use Phly\KeepAChangelog\Common\ChangelogEntry;
use Phly\KeepAChangelog\Common\Editor;

use function file_exists;
use function file_get_contents;
use function file_put_contents;
use function is_string;
use function sprintf;
use function sys_get_temp_dir;
use function uniqid;
use function unlink;

class EditChangelogLinksListener
{
    public function __invoke(EditChangelogLinksEvent $event) : void
    {
        $changelog = $event->config()->changelogFile();
        $links     = $event->links();
        $contents  = $links instanceof ChangelogEntry ? $links->contents : '';
        $tempFile  = $this->createTempFileWithContents($contents);

        $status = $this->getEditor()->spawnEditor(
            $event->output(),
            $event->editor(),
            $tempFile
        );

        if (0 !== $status) {
            $this->unlinkTempFile($tempFile);
            $event->editFailed($changelog);
            return;
        }

        $linkContents = file_get_contents($tempFile);
        $editor       = $this->getChangelogEditor();

        $this->unlinkTempFile($tempFile);

        $links instanceof ChangelogEntry
            ? $editor->update($changelog, $linkContents, $links)
            : $editor->append($changelog, $linkContents);

        $event->editComplete($changelog);
    }

    /**
     * Creates a temporary file with the changelog contents.
     */
    private function createTempFileWithContents(string $contents) : string
    {
        if (is_string($this->mockTempFile)) {
            return $this->mockTempFile;
        }

        $filename = sprintf('%s.md', uniqid('KAC', true));
        $path     = sprintf('%s/%s', sys_get_temp_dir(), $filename);

        file_put_contents($path, $contents);

        return $path;
    }

    /**
     * Removes the temp file generated by createTempFileWithContents
     */
    private function unlinkTempFile(string $filename) : void
    {
        if (is_string($this->mockTempFile) || ! file_exists($filename)) {
            return;
        }

        unlink($filename);
    }

    private function getChangelogEditor() : ChangelogEditor
    {
        if ($this->changelogEditor instanceof ChangelogEditor) {
            return $this->changelogEditor;
        }

        return new ChangelogEditor();
    }

    private function getEditor() : Editor
    {
        if ($this->editor instanceof Editor) {
            return $this->editor;
        }

        return new Editor();
    }

    /**
     * Provide a ChangelogEditor instance to use.
     *
     * For testing purposes only.
     *
     * @internal
     * @var null|ChangelogEditor
     */
    public $changelogEditor;

    /**
     * Provide an Editor instance to use.
     *
     * For testing purposes only.
     *
     * @internal
     * @var null|Editor
     */
    public $editor;

    /**
     * Provide a mock temporary filename.
     *
     * For testing purposes only.
     *
     * @internal
     * @var null|string
     */
    public $mockTempFile;
}
